language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - mkdir build
  - cp -a ./ ./build/
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target-branch: master
  keep-history: true
  on:
    branch: master
